### PR TITLE
fix: Read from Oldest Offset for Idle Source Kafka e2e 

### LINKED ISSUE #1727: Flaky reduce-two-e2e and idle-source-e2e
reduce-two-e2e - https://github.com/numaproj/numaflow/actions/runs/9034959063/job/24828692966?pr=1723
idle-source-e2e - https://github.com/numaproj/numaflow/actions/runs/9026274446/job/24803315933

### PR DESCRIPTION
**Pull request by yhl25**
fixes #1727

### CODE REVIEW

File: test/idle-source-e2e/idle_source_test.go [hunk 1]
```diff
@@ -115,26 +112,27 @@ func (is *IdleSourceSuite) TestIdleKeyedReducePipelineWithKafkaSource() {
...
 			default:
-				// send message to both partition for first 1000 messages for overcome the kafka source lazy loading wm publisher.
+				// send message to both partition for first 600 messages for overcome the kafka source lazy loading wm publisher.
 				// after that send message to only one partition. so that idle source will be detected and wm will be progressed.
 				SendMessage(topic, "data", generateMsg("1", startTime), 0)
-				if i < 2000 {
+				if i < 600 {
 					SendMessage(topic, "data", generateMsg("2", startTime), 1)
 				}
+				time.Sleep(100 * time.Millisecond)
```
Comment (vigith) [inline test/idle-source-e2e/idle_source_test.go:129]: isn't this sleep a lot for 600 messages?

**Review by vigith — APPROVED** [review]

File: test/idle-source-e2e/idle_source_test.go (hunk 1 above)
Comment (yhl25) [reply test/idle-source-e2e/idle_source_test.go:129]: We give about 1 minute for Kafka partition lazy loading. It might not take that long, but sometimes creating a Kafka consumer can take a while.
