### PR TITLE
feat(controller): fix scaling for ordered processing and validations

### LINKED ISSUE #3272: Controller to use fixed min/max scale with Ordered Processing
# Summary

Controller should set min and max replicas to same as the number of partitions set. We should disable the autoscaling when ordered processing is configured. This is because each partition can be only processed by one pod.

### Validations
Validations are only applicable to Map and Sink vertices. Source is always ordered and Reduce does not required ordering.
* If partitions is not set, then we should throw an error
* Validation should fail if scale is set by user.

### PR DESCRIPTION
**Pull request by vigith**
Closes #3272

### CODE REVIEW

File: pkg/reconciler/validator/pipeline_validate.go [hunk 1]
```diff
@@ -773,15 +773,42 @@ func validateSQSSink(sqs dfv1.SqsSink) error {
...
 
-	// Vertex-level validation: ensure vertex-level ordered config is valid.
-	// Since it's just a boolean field, no additional validation is needed.
-	// Reduce vertices will ignore this setting (handled in GetEffectiveOrderedConfig).
+		// For map and sink vertices with ordered processing enabled:
+
+		// 1. Partitions must be set
+		if v.Partitions == nil || *v.Partitions <= 0 {
+			return fmt.Errorf("vertex %q: partitions must be set and greater than 0 when ordered processing is enabled", v.Name)
+		}
```
Comment (vigith) [inline pkg/reconciler/validator/pipeline_validate.go]: we cannot scale to 0.

File: pkg/reconciler/pipeline/controller.go [hunk 2]
```diff
@@ -661,8 +661,19 @@ func buildVertices(pl *dfv1.Pipeline) map[string]dfv1.Vertex {
...
+		} else if v.GetEffectiveOrderedConfig(pl.Spec.Ordered) && (v.IsMapUDF() || v.IsASink()) {
+			// For map and sink vertices with ordered processing enabled, set replicas to partition count
+			// This ensures each partition is processed by exactly one pod for ordered processing
+			// Note: Source vertices are always ordered, reduce vertices are already handled above
+			partitions := pl.NumOfPartitions(v.Name)
+			replicas = int32(partitions)
+			// Disable autoscaling for ordered processing vertices by setting min = max = partitions
+			vCopy.Scale.Disabled = true
+			vCopy.Scale.Min = &replicas
+			vCopy.Scale.Max = &replicas
```
Comment (yhl25) [inline pkg/reconciler/pipeline/controller.go:676]: Should we override the value or throw a validation error so that user can set it?

Comment (vigith) [reply pkg/reconciler/pipeline/controller.go:676]: we throw validation error https://github.com/numaproj/numaflow/pull/3281/changes#diff-e474f76c584e90fc6e5032ecf11887abcacb844443dec8e431933aa53e2c99abR808-R810

File: pkg/reconciler/validator/pipeline_validate.go [hunk 3]
```diff
@@ -773,15 +773,42 @@ func validateSQSSink(sqs dfv1.SqsSink) error {
...
+			continue
+		}
 
-	// Vertex-level validation: ensure vertex-level ordered config is valid.
-	// Since it's just a boolean field, no additional validation is needed.
-	// Reduce vertices will ignore this setting (handled in GetEffectiveOrderedConfig).
+		// For map and sink vertices with ordered processing enabled:
+
+		// 1. Partitions must be set
+		if v.Partitions == nil || *v.Partitions <= 0 {
```
Comment (yhl25) [inline pkg/reconciler/validator/pipeline_validate.go]: Should we default to 1?

File: pkg/reconciler/validator/pipeline_validate.go [hunk 4]
```diff
@@ -773,15 +773,42 @@ func validateSQSSink(sqs dfv1.SqsSink) error {
...
+			return fmt.Errorf("vertex %q: partitions must be set and greater than 0 when ordered processing is enabled", v.Name)
+		}
+
+		// 2. Scale config (min/max) must not be set by user
+		// Users should not configure autoscaling for ordered processing vertices
+		if v.Scale.Min != nil || v.Scale.Max != nil {
+			return fmt.Errorf("vertex %q: scale (min/max) should not be set when ordered processing is enabled. Replicas will be fixed to partition count", v.Name)
```
Comment (yhl25) [inline pkg/reconciler/validator/pipeline_validate.go]: Do we fail even if users has set min and max the same as the partition count?

Comment (vigith) [reply pkg/reconciler/validator/pipeline_validate.go]: Yes, if `!nil`, it will fail

Comment (yhl25) [reply pkg/reconciler/validator/pipeline_validate.go]: But that is a valid config right?
