### PR TITLE
chore: fix data race in reduce tests

### LINKED ISSUE #586: TestReduceDataForward_Sum has data race
`TestReduceDataForward_Sum` is failing because it is publishing and reading concurrently. This behaviour only happens in the test because we run both producer and consumer at the same time. 

I prefer not to add locks in publisher.go because it will hurt the performance

```==================
WARNING: DATA RACE
Write at 0x00c0002de278 by goroutine 422:
  github.com/numaproj/numaflow/pkg/watermark/publish.(*publish).validateWatermark()
      /home/runner/work/numaflow/numaflow/pkg/watermark/publish/publisher.go:145 +0x49e
  github.com/numaproj/numaflow/pkg/watermark/publish.(*publish).PublishWatermark()
      /home/runner/work/numaflow/numaflow/pkg/watermark/publish/publisher.go:99 +0x92
  github.com/numaproj/numaflow/pkg/reduce.publishMessages()
      /home/runner/work/numaflow/numaflow/pkg/reduce/data_forward_test.go:873 +0x63b
  github.com/numaproj/numaflow/pkg/reduce.TestReduceDataForward_Sum.func6()
      /home/runner/work/numaflow/numaflow/pkg/reduce/data_forward_test.go:407 +0xef

Previous read at 0x00c0002de278 by goroutine 416:
  github.com/numaproj/numaflow/pkg/watermark/publish.(*publish).validateWatermark()
      /home/runner/work/numaflow/numaflow/pkg/watermark/publish/publisher.go:147 +0x55e
  github.com/numaproj/numaflow/pkg/watermark/publish.(*publish).PublishIdleWatermark()
      /home/runner/work/numaflow/numaflow/pkg/watermark/publish/publisher.go:159 +0xbb
  github.com/numaproj/numaflow/pkg/reduce/pnf.(*ProcessAndForward).publishWM()
      /home/runner/work/numaflow/numaflow/pkg/reduce/pnf/processandforward.go:269 +0x483
  github.com/numaproj/numaflow/pkg/reduce/pnf.(*ProcessAndForward).Forward()
      /home/runner/work/numaflow/numaflow/pkg/reduce/pnf/processandforward.go:150 +0x82c
  github.com/numaproj/numaflow/pkg/reduce/readloop.(*orderedForwarder).forward()
      /home/runner/work/numaflow/numaflow/pkg/reduce/readloop/ordered.go:183 +0x1473
  github.com/numaproj/numaflow/pkg/reduce/readloop.newOrderedForwarder.func1()
      /home/runner/work/numaflow/numaflow/pkg/reduce/readloop/ordered.go:71 +0x58

Goroutine 422 (running) created at:
  github.com/numaproj/numaflow/pkg/reduce.TestReduceDataForward_Sum()
      /home/runner/work/numaflow/numaflow/pkg/reduce/data_forward_test.go:407 +0x8f9
  testing.tRunner()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1493 +0x47

Goroutine 416 (running) created at:
  github.com/numaproj/numaflow/pkg/reduce/readloop.newOrderedForwarder()
      /home/runner/work/numaflow/numaflow/pkg/reduce/readloop/ordered.go:71 +0x378
  github.com/numaproj/numaflow/pkg/reduce/readloop.NewReadLoop()
      /home/runner/work/numaflow/numaflow/pkg/reduce/readloop/readloop.go:81 +0xc4
  github.com/numaproj/numaflow/pkg/reduce.NewDataForward()
      /home/runner/work/numaflow/numaflow/pkg/reduce/data_forward.go:79 +0x2d5
  github.com/numaproj/numaflow/pkg/reduce.TestReduceDataForward_Sum()
      /home/runner/work/numaflow/numaflow/pkg/reduce/data_forward_test.go:399 +0x669
  testing.tRunner()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1446 +0x216
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1493 +0x47
==================
{"level":"info","ts":1677885385.6130238,"logger":"numaflow","caller":"readloop/readloop.go:408","msg":"Close of book","partitionID":"120000-240000"}
{"level":"warn","ts":1677885385.6133683,"logger":"numaflow","caller":"publish/publisher.go:147","msg":"Skip publishing the new watermark because it's older than the current watermark","entityID":"source-reduce-buffer","otStore":"TestReduceDataForward_Sum_OT","hbStore":"TestReduceDataForward_Sum_PROCESSORS","head":"1970-01-01T00:04:59Z","new":"1970-01-01T00:02:00Z"}
    testing.go:1319: race detected during execution of test
--- FAIL: TestReduceDataForward_Sum (0.15s)
```

### PR DESCRIPTION
**Pull request by yhl25**
fixes #586

### CODE REVIEW

File: pkg/reduce/pbq/pbq.go [hunk 1]
```diff
@@ -86,7 +88,13 @@ func (p *PBQ) CloseOfBook() {
 // Close is used by the writer to indicate close of context
 // we should flush pending messages to store
 func (p *PBQ) Close() error {
-	return p.store.Close()
+	p.mu.Lock()
```
Comment (ashwinidulams) [inline pkg/reduce/pbq/pbq.go:91]: this is accessed by only one routine at any point in time right?

Comment (ashwinidulams) [reply pkg/reduce/pbq/pbq.go:91]: i see. GC will cause the store to be set to nil, where as the store.Close() could be invoked. ok makes sense.

**Review by vigith — APPROVED** [review]
