### PR TITLE
fix: Dedup not working for multi-partitioned edge

### LINKED ISSUE #1634: Track read metrics at partition level for user defined source
This will help us understand lagging and stuck readers and also the data distribution.

### LINKED ISSUE #1635: Dedup not working as expected when using multi-partitioned edges

### PR DESCRIPTION
**Pull request by yhl25**
fixes #1635 
fixes #1634

### CODE REVIEW

File: pkg/sources/source.go [hunk 1]
```diff
@@ -175,7 +175,7 @@ func (sp *SourceProcessor) Start(ctx context.Context) error {
 	var toVertexPartitionMap = make(map[string]int)
 	shuffleFuncMap := make(map[string]*shuffle.Shuffle)
 	for _, edge := range sp.VertexInstance.Vertex.Spec.ToEdges {
-		if edge.ToVertexType == dfv1.VertexTypeReduceUDF && edge.GetToVertexPartitionCount() > 1 {
+		if edge.GetToVertexPartitionCount() > 1 {
```
Comment (whynowy) [inline pkg/sources/source.go:178]: Was this something we forgot to change when working on multi-partition support?

Comment (vigith) [reply pkg/sources/source.go:178]: we are adding message-id based shuffling for every vertex. this is to have deterministic writing when we have multi-partitioned edges and dedupe will work correctly because dedupe is per stream.

**Review by vigith — APPROVED** [review]

File: pkg/forwarder/interfaces.go [hunk 2]
```diff
@@ -25,17 +25,18 @@ type VertexBuffer struct {
 // ToWhichStepDecider decides which step to forward after applying the WhereTo function.
 type ToWhichStepDecider interface {
 	// WhereTo decides where to forward the result to based on the name of the step it returns.
+	// It is deterministic and will forward the same message-id to the partition using a hashing algorithm.
 	// It supports 2 addition keywords which need not be a step name. They are "ALL" and "DROP"
 	// where former means, forward to all the neighbouring steps and latter means do not forward anywhere.
-	WhereTo([]string, []string) ([]VertexBuffer, error)
+	WhereTo([]string, []string, string) ([]VertexBuffer, error)
```
Comment (whynowy) [inline pkg/forwarder/interfaces.go:31]: Can we rewrite the docs above, and explain the args accepted? I feel like the docs have drifted too much, and no one understands what they tell.
