### PR TITLE
fix: Progress watermark for a source idling from the start

### LINKED ISSUE #3006: Support idleSource detection for empty sources
# Summary

[idleSource](https://numaflow.numaproj.io/core-concepts/watermarks/#idle-detection) should be able to progress the watermark on a source, in situations where the source has never received any data.

Currently, a watermark on the source is not set (or technically initiated to epoch 0) until the first event with event-time is received. `idleSource` is hereafter able to detect gaps in data of duration `threshold`. But, if a first event is never received, `idleSource` has no effect.

The proposal is, that idleSource can set the watermark equal to processing-time (wall-clock time) after `threshold` time has passed in the processor. (Possible `threshold+maxDelay`?).

Numaflows watermark-design is based on event time, and a coupling the process-time should generally be avoided. However, the `idleSource` is already using process-time as the max bound a watermark can progress to. Especially in settings where `stepInterval: 0s` (default setting), the watermark is effectively already incremented at instant speed to the current wall-time (or at least very near due to the finite `incrementBy`).

Add a config setting to enable this feature.

(Need to be aware of the general startup time of pipeline/pods - How to avoid that normally starting pipeline is not overrun by this feature, causing data-loss from all input streams. Should at least one stream have watermark set before this feature can trigger?)

# Use Cases

For pipelines with two or more sources joined into and accumulator or reducer vertex.
Where accumulator/reducer vertex has limited memory resources (e.g. `scale.max: 1` for ordering-guarantee and `limits.memory` set).
In the situation where the pipeline is starting up, but one of the multiple sources does not generate data, all other source will keep feeding data greedily into the accumulator/reducer, eventually causing OutOfMemory/Crashloopbackoff. The the accumulator/reducer pod restart, it will again greedily read all data from the ISB stream and crash again. Creating/recreating pipelines from current-source-offsets, thus only works, if all sources has data at the simultaneous starting point.

# Reproducible Example / Test

The following example can be used to reproduce the issue and test the new feature.

- Install numaflow 1.5.1 (helm 0.2.1) for accumulator support.
- Clone [accumulator/streamsorter](https://github.com/numaproj/numaflow-go/tree/main/examples/accumulator/streamsorter)
- Add `idleSource` and `limits` in the manifest:
```yaml
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: stream-sorter
spec:
  watermark:
    idleSource:
      threshold: "5s"
      incrementBy: "3s"
      stepInterval: "2s"
  limits:
    readBatchSize: 1
  vertices:
    - name: http-one
      scale:
        min: 1
        max: 1
      source:
        http: {}
    - name: http-two
      scale:
        min: 1
        max: 1
      source:
        http: {}
    - name: accum
      udf:
        container:
          image: quay.io/numaio/numaflow-go/stream-sorter:stable
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 32Mi
        groupBy:
          window:
            accumulator:
              timeout: 10s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 1Gi
      containerTemplate:
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
      scale:
        min: 1
        max: 1
    - name: sink
      scale:
        min: 1
        max: 1
      sink:
        log: {}
  edges:
    - from: http-one
      to: accum
    - from: http-two
      to: accum
    - from: accum
      to: sink
```
- `kubectl apply -f manifest/stream-sorter-pipeline.yaml` and let the pipeline start.
- `kubectl port-forward stream-sorter-http-one-0-xxxx 8444:8443` (only http-one)
- `yes '{"key":"value"}' | head -c 100000 > payload_100kB.json`
- `watch -n 0.1 'curl -kq -X POST --data-binary @payload_100kB.json https://localhost:8444/vertices/http-one'`
- The data never reaches sink. After ~1min the accumulator memory is reached and CrashLoopReboot occurs.

The expected output is that all data from http-one reaches sink.

(Maybe a caveat on how the new feature can cause data loss in beginning of even the earliest producing stream, here http-one.)

Image

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by vaibhavtiwari33**
## What this PR does / why we need it

Related issue describes in quite detail the problem statement this PR aims to solve. 

## Related issues
Fixes #3006

## Testing
How was this tested (unit/integration/manual)? Include commands, links, or screenshots if applicable.

### Test with local pipeline

Spec utilized:
```yaml
spec:
  vertices:
    - name: http-one
      scale:
        min: 1
        max: 1
      source:
        http: {}
    - name: input-two
      source:
        generator:
          rpu: 50
          duration: 1s
          keyCount: 1
    - name: sorter
      udf:
        container:
          image: quay.io/numaio/numaflow-go/stream-sorter:stable
        groupBy:
          window:
            accumulator:
              timeout: 10s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 1Gi
    - name: sink
      scale:
        min: 1
        max: 1
      sink:
        log: {}
  edges:
    - from: http-one
      to: sorter
    - from: input-two
      to: sorter
    - from: sorter
      to: sink
```

* With one source never producing any data, the pipeline is stuck with no data emitted to sink:

WithoutchangesPipeline

WithoutchangesSink

* After adding the watermark idleConfig (without InitSourceDelay), the pipeline remains stuck:

```yaml
watermark:
    maxDelay: 0s
    idleSource:
      threshold: 5s
      stepInterval: 2s
      incrementBy: 1s
```
BeforeSpec

WithChangesPipeline

WithChangesSink

* Initializing the InitSourceDelay allows progression of watermark for inactive source:

```yaml
watermark:
    maxDelay: 0s
    idleSource:
      threshold: 5s
      stepInterval: 2s
      incrementBy: 1s
      initSourceDelay: 5s
```

AfterSpec
WithSourceInitDelayPipeline

WithSourceInitDelaySink

### CODE REVIEW

File: rust/numaflow-core/src/watermark/idle/source.rs [hunk 1]
```diff
@@ -50,6 +50,25 @@ impl SourceIdleDetector {
             >= self.config.threshold.as_millis() as i64
     }
 
+    fn get_source_idling_from_init_wm(&mut self) -> i64 {
+        if let Some(init_source_delay) = self.config.init_source_delay
+            && Utc::now().timestamp_millis() - self.updated_ts.timestamp_millis()
+                >= init_source_delay.as_millis() as i64
+        {
+            let now = Utc::now();
```
Comment (yhl25) [inline rust/numaflow-core/src/watermark/idle/source.rs]: avoid branching by using `let Some(x) = x else {}` ?

Comment (vaibhavtiwari33) [reply rust/numaflow-core/src/watermark/idle/source.rs]: Sure, I can do that, it required returning -1 twice with the second conditional, so it looked a little ugly to me, that's all. Let me change back

Comment (vaibhavtiwari33) [reply rust/numaflow-core/src/watermark/idle/source.rs]: Updated

File: rust/numaflow-core/src/watermark/idle/source.rs [hunk 2]
```diff
@@ -50,6 +50,27 @@ impl SourceIdleDetector {
...
+
+        let Some(init_source_delay) = self.config.init_source_delay else {
+            return -1;
+        };
+
+        if now.timestamp_millis() - self.updated_ts.timestamp_millis()
+            >= init_source_delay.as_millis() as i64
+        {
+            let idle_wm = now.timestamp_millis() + init_source_delay.as_millis() as i64;
+            self.last_idle_wm_published_time = now;
```
Comment (vigith) [inline rust/numaflow-core/src/watermark/idle/source.rs:66]: why are we adding? shouldn't it be just "now"?

Comment (vaibhavtiwari33) [reply rust/numaflow-core/src/watermark/idle/source.rs:66]: That's a good point. Let me fix this
