### PR TITLE
fix: e2e testing for PBQ WAL with reduce pipeline

### LINKED ISSUE #392: e2e testing for PBQ WAL with reducer pipeline

### PR DESCRIPTION
**Pull request by xdevxy**
Signed-off-by: Hao Hao <xdevxhao@gmail.com>

Add e2e test for PBQ WAL failover with a simple reduce pipeline. Closes #392 .

### CODE REVIEW

File: test/reducer-e2e/reducer_test.go [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+					Status(204)
+			}
+		}
+
+		w.Expect().VertexPodLogContains("sink", "Payload -  120")
+		w.Expect().VertexPodLogContains("sink", "Payload -  240")
+	}()
+
+	// Kill one of the pod during processing to trigger failover.
+	block := func(t *testing.T, output string, err error) {
```
Comment (vigith) [inline test/reducer-e2e/reducer_test.go:63]: should we initiate a kill at a very specific point eg, at `i=x && j=y`? this will ensure that we do not kill at random points which could end up being flaky.

Comment (vigith) [inline test/reducer-e2e/reducer_test.go:63]: I am also thinking about whether this should be a utility function that can be used in other tests too.

Comment (xdevxy) [reply test/reducer-e2e/reducer_test.go:63]: This is to mimic that failure (or pod migration) can happen at any moment during pipeline execution and still get the correct result. If there is any flakiness due to this, I think we should investigate and check what is the cause.

Comment (xdevxy) [reply test/reducer-e2e/reducer_test.go:63]: Yeah, I guess only thing may be depends on the scenarios, one may want to take different actions towards the value of `output` or `err`

Comment (vigith) [reply test/reducer-e2e/reducer_test.go:63]: such random testing shouldn't be done in e2e tests. E2E tests should be predictable. Such random tests can be labeled, perhaps under Fuzz tests or something.

There are three major of pod migration scenarios
* right before processing
* during processing
* right after processing

Comment (vigith) [reply test/reducer-e2e/reducer_test.go:63]: such random testing shouldn't be done in e2e tests. E2E tests should be predictable. Such random tests can be labeled, perhaps under Fuzz tests or something.

There are three major of pod migration scenarios
* right before processing
* during processing
* right after processing

Comment (vigith) [reply test/reducer-e2e/reducer_test.go:63]: are we interpreting the result of `output` or `err` on pod kill?

Comment (xdevxy) [reply test/reducer-e2e/reducer_test.go:63]: Do you want me to rename the the test or create a new folder for fuzz tests and put it under it? I can add the other two scenarios, for `right before processing` and `right after processing` I didn't add previously as the behavior shouldn't differ with or without WAL implementation.

Comment (vigith) [reply test/reducer-e2e/reducer_test.go:63]: Let's not do fuzz testing now. Instead, let's make this E2E test complete by adding the 3 scenarios I have mentioned.

Comment (vigith) [reply test/reducer-e2e/reducer_test.go:63]: Yes, that is the expected behavior of `deleted` right? Hence I am suggesting we make it reusable. I can't think of any other checks, do you envision any?

Comment (whynowy) [reply test/reducer-e2e/reducer_test.go:63]: @xdevxy - let's do following:

1. Create the pipeline, expect both reduce pods running;
2. Kill them both;
3. Start ingesting messages, pause when half is done;
4. Expect both reduce pods running, and kill them again;
5. Finish ingesting;
6. Expect the results,
7. Kill them again, and no result changes expected.

File: test/reduce-e2e/reduce_test.go [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+		VertexPodsRunning().DaemonPodsRunning().
+		VertexPodLogContains("in", LogSourceVertexStarted).
+		VertexPodLogContains("atoi", LogUDFVertexStarted, PodLogCheckOptionWithContainer("numa")).
+		VertexPodLogContains("sink", LogSinkVertexStarted).
+		DaemonPodLogContains(pipelineName, LogDaemonStarted)
+
+	defer w.VertexPodPortForward("in", 8443, dfv1.VertexHTTPSPort).
+		TerminateAllPodPortForwards()
+
+	args := "kubectl delete po `kubectl -n numaflow-system get po " +
```
Comment (whynowy) [inline test/reduce-e2e/reduce_test.go]: Is this used to kill both? If that the case, use following.

```shell
kubectl -n numaflow-system delete po -l numaflow.numaproj.io/pipeline-name=even-odd-sum,numaflow.numaproj.io/vertex-name=compute-sum
```

File: test/fixtures/util.go [hunk 3]
```diff
@@ -48,6 +48,11 @@ var OutputRegexp = func(rx string) func(t *testing.T, output string, err error)
 	}
 }
 
+var CheckPodKillSucceed = func(t *testing.T, output string, err error) {
```
Comment (whynowy) [inline test/fixtures/util.go:51]: `Succeeded`

File: test/reduce-e2e/reduce_test.go [hunk 4]
```diff
@@ -0,0 +1,84 @@
...
+		"-lnumaflow.numaproj.io/pipeline-name=even-odd-sum,numaflow.numaproj.io/vertex-name=compute-sum | " +
+		"grep -v NAME | head -2 | awk '{print $1}'`"
+
+	// Kill one of the pod before processing to trigger failover.
```
Comment (whynowy) [inline test/reduce-e2e/reduce_test.go:41]: This is killing both, not one, right?

File: test/reduce-e2e/reduce_test.go [hunk 5]
```diff
@@ -0,0 +1,78 @@
...
+	args := "kubectl delete po `kubectl -n numaflow-system get po " +
+		"-lnumaflow.numaproj.io/pipeline-name=even-odd-sum,numaflow.numaproj.io/vertex-name=compute-sum | " +
+		"grep -v NAME | head -1 | awk '{print $1}'`"
+
+	// Kill one of the pod before processing to trigger failover.
+	w.Exec("/bin/sh", []string{"-c", args}, CheckPodKillSucceed)
+
+	startTime := int(time.Unix(1000, 0).UnixMilli())
+	for i := 1; i <= 100; i++ {
+		for j := 0; j < 1; j++ {
```
Comment (whynowy) [inline test/reduce-e2e/reduce_test.go:46]: What is the for loop for?

File: test/reduce-e2e/reduce_test.go [hunk 6]
```diff
@@ -0,0 +1,78 @@
...
+				Expect().
+				Status(204)
+		}
+	}
+
+	w.Expect().VertexPodLogContains("sink", "Payload -  120")
+	w.Expect().VertexPodLogContains("sink", "Payload -  240")
+
+	// Kill one of the pod after processing to trigger failover.
+	w.Exec("/bin/sh", []string{"-c", args}, CheckPodKillSucceed)
```
Comment (whynowy) [inline test/reduce-e2e/reduce_test.go:71]: Add a new pods running check, this is to make sure there's no result change (e.g., duplicate) after they start.

File: test/reduce-e2e/reduce_test.go [hunk 7]
```diff
@@ -0,0 +1,78 @@
...
+	w.Expect().VertexPodLogContains("sink", "Payload -  120")
```
Comment (whynowy) [inline test/reduce-e2e/reduce_test.go:72]: Use `PodLogCheckOptionWithCount` option.

File: test/reduce-e2e/reduce_test.go [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+	w.Expect().
+		VertexPodLogContains("in", LogSourceVertexStarted).
+		VertexPodLogContains("atoi", LogUDFVertexStarted, PodLogCheckOptionWithContainer("numa")).
+		VertexPodLogContains("sink", LogSinkVertexStarted).
+		DaemonPodLogContains(pipelineName, LogDaemonStarted)
+
+	defer w.VertexPodPortForward("in", 8443, dfv1.VertexHTTPSPort).
+		TerminateAllPodPortForwards()
+
+	args := "kubectl delete po -n numaflow-system `kubectl -n numaflow-system get po " +
```
Comment (whynowy) [inline test/reduce-e2e/reduce_test.go:37]: Is this used to kill both pods? If that's the case, use 

```shell
kubectl -n numaflow-system delete po -l numaflow.numaproj.io/pipeline-name=even-odd-sum,numaflow.numaproj.io/vertex-name=compute-sum
```

File: test/reduce-e2e/reduce_test.go [hunk 9]
```diff
@@ -0,0 +1,97 @@
...
+
+	defer w.VertexPodPortForward("in", 8443, dfv1.VertexHTTPSPort).
+		TerminateAllPodPortForwards()
+
+	args := "kubectl delete po -n numaflow-system -l " +
+		"numaflow.numaproj.io/pipeline-name=even-odd-sum,numaflow.numaproj.io/vertex-name=compute-sum"
+
+	// Kill the reducer pods before processing to trigger failover.
+	w.Exec("/bin/sh", []string{"-c", args}, CheckPodKillSucceeded)
+	w.Expect().VertexPodsRunning()
```
Comment (whynowy) [inline test/reduce-e2e/reduce_test.go:58]: This line could be removed - we would expect after killing 2 reduce pods, the ingested data would still be picked up later one when they came back.

**Review by whynowy — COMMENTED** [review]
All the reset looks good to me.

File: test/reduce-e2e/reduce_test.go [hunk 10]
```diff
@@ -0,0 +1,97 @@
...
+
+	startTime := int(time.Unix(1000, 0).UnixMilli())
+	for i := 1; i <= 100; i++ {
+		eventTime := startTime + (i * 1000)
+		if i == 5 {
+			// Kill the reducer pods during processing to trigger failover.
```
Comment (whynowy) [inline test/reduce-e2e/reduce_test.go:64]: Move the line 58 here.

**Review by whynowy — APPROVED** [review]
