### PR TITLE
fix: return none, if any of the Vn-1 processors are not idle

### LINKED ISSUE #2956: Tracker does not maintain idle state

### PR DESCRIPTION
**Pull request by yhl25**
Closes #2956

### CODE REVIEW

File: rust/numaflow-core/src/pipeline/isb/jetstream/reader.rs [hunk 1]
```diff
@@ -306,6 +306,19 @@ impl<C: NumaflowTypeConfig> JetStreamReader<C> {
...
+                    // Update tracker idle status based on whether we read any messages
+                    if read_messages.is_empty() {
+                        // No messages read, set tracker to idle
+                        if let Err(e) = self.tracker_handle.set_idle_status(true).await {
+                            warn!(?e, "Failed to set tracker idle status to true");
+                        }
+                    } else {
+                        // Messages read, set tracker to not idle
+                        if let Err(e) = self.tracker_handle.set_idle_status(false).await {
+                            warn!(?e, "Failed to set tracker idle status to false");
```
Comment (vigith) [inline rust/numaflow-core/src/pipeline/isb/jetstream/reader.rs]: use optimistic locking, use WMB offset in the idle field and when publishing make sure head WMB matches the one registered by the tracker's idle field.

**Review by vigith — APPROVED** [review]
