### PR TITLE
fix: best effort processing during SIGTERM. Closes #371

### LINKED ISSUE #371: readloop ends up with partial acks during SIGTERM
Any error short circuits the forward loop and the ctx.Done() is also sometimes misinterpreted as as error. We should try to process all successful entries from the previous step in the subsequent steps.

### PR DESCRIPTION
**Pull request by vigith**
Fixes: #371 

Process all the successful entries returned by the previous step in the subsequent steps.

Signed-off-by: Vigith Maurice <vigith@gmail.com>

### CODE REVIEW

File: pkg/reduce/readloop/readloop.go [hunk 1]
```diff
@@ -115,87 +115,156 @@ func (rl *ReadLoop) Startup(ctx context.Context) error {
...
+				rl.log.Errorw("Failed to ack message", zap.String("msgOffSet", m.ReadOffset.String()), zap.Error(rErr))
+				// no point retrying if ctx.Done has been invoked
+				select {
+				case <-ctx.Done():
+					// no point in retrying after we have been asked to stop.
+					return false, ctx.Err()
+				default:
+					// keep retrying
 					return false, nil
 				}
```
Comment (yhl25) [inline pkg/reduce/readloop/readloop.go:254]: This can be achieved by using ExponentialBackoffWithContext

File: pkg/reduce/readloop/readloop.go [hunk 2]
```diff
@@ -115,87 +115,156 @@ func (rl *ReadLoop) Startup(ctx context.Context) error {
...
-				partitions := cw.Partitions()
-				rl.closePartitions(partitions)
-				rl.log.Debugw("Closing Window", zap.Time("windowStart", cw.StartTime()), zap.Time("windowEnd", cw.EndTime()))
-			}
+			return true, nil
+		})
+		// no point trying the rest of the message, most likely that will also fail
+		if err != nil {
+			rl.log.Errorw("Failed to ack message, exiting the loop", zap.Error(err))
+			break
```
Comment (yhl25) [inline pkg/reduce/readloop/readloop.go:263]: What if the writes to the PQB were successful and while acking those messages you received a ctx.done? Before you return you should ack all the messages in that batch right?

File: pkg/reduce/readloop/readloop.go [hunk 3]
```diff
@@ -115,87 +115,156 @@ func (rl *ReadLoop) Startup(ctx context.Context) error {
...
 
-			// Ack the message to ISB
-			attempt := 0
-			timeoutErr := wait.ExponentialBackoff(pbqWriteBackoff, func() (done bool, err error) {
-				rErr := m.ReadOffset.AckIt()
-				attempt += 1
-				if rErr != nil {
-					rl.log.Errorw("Failed to ack message", zap.String("msgOffSet", m.ReadOffset.String()), zap.Int("attempt", attempt), zap.Error(rErr))
+// ackMessages acks messages. Retries until it can succeed or ctx.Done() happens.
+func (rl *ReadLoop) ackMessages(ctx context.Context, messages []*isb.ReadMessage) error {
```
Comment (ashwinidulams) [inline pkg/reduce/readloop/readloop.go:232]: does it make sense to combine this with the write operation? ack as soon as you write the message.

File: pkg/reduce/readloop/readloop.go [hunk 4]
```diff
@@ -115,87 +115,156 @@ func (rl *ReadLoop) Startup(ctx context.Context) error {
...
 }
 
-// Process is one iteration of the read loop.
+// Process is one iteration of the read loop which writes the messages to the PBQs followed by acking the messages, and
+// then closing the windows that can closed.
 func (rl *ReadLoop) Process(ctx context.Context, messages []*isb.ReadMessage) {
-	// There is no Cap on backoff because setting a Cap will result in
-	// backoff stopped once the duration exceeds the Cap
+	// write messages to windows based by PBQs.
+	successfullyWrittenMessages, err := rl.writeMessagesToWindows(ctx, messages)
```
Comment (ashwinidulams) [inline pkg/reduce/readloop/readloop.go:122]: To guarantee acks, we need to handle the context Done event here in addition to write

Comment (vigith) [reply pkg/reduce/readloop/readloop.go:122]: why do we need to do that?

File: pkg/reduce/readloop/readloop.go (hunk 1 above)
Comment (vigith) [reply pkg/reduce/readloop/readloop.go:254]: `ExponentialBackoffWithContext` will not work because it will return without executing anything if `ctx.Done()` has been closed. https://github.com/kubernetes/apimachinery/blob/v0.25.4/pkg/util/wait/wait.go#L734-L738

File: pkg/reduce/readloop/readloop.go (hunk 2 above)
Comment (vigith) [reply pkg/reduce/readloop/readloop.go:263]: That should be fine, this `break` is to get out of the loop only if the `Ack` is failing. Otherwise, it will run to completion.

File: pkg/reduce/readloop/readloop.go (hunk 4 above)
Comment (vigith) [reply pkg/reduce/readloop/readloop.go:122]: We check for `ctx.Done()` befeore every batch iteration in https://github.com/numaproj/numaflow/blob/a19f77c017ddd706d4e6c2e15d457e34757c604a/pkg/reduce/reduce.go#L89-L91

Comment (ashwinidulams) [reply pkg/reduce/readloop/readloop.go:122]: i guess thats fine. since we are cancelling it after we close the read, this should work.

**Review by ashwinidulams — APPROVED** [review]

File: pkg/reduce/readloop/readloop.go (hunk 1 above)
Comment (yhl25) [reply pkg/reduce/readloop/readloop.go:254]: yeah makes sense

File: pkg/reduce/readloop/readloop.go (hunk 2 above)
Comment (yhl25) [reply pkg/reduce/readloop/readloop.go:263]: okay

**Review by yhl25 — APPROVED** [review]
