### PR TITLE
fix: dedup in user defined source

### LINKED ISSUE #1611: User-defined source write metrics not matching the read metrics from next vertex
**Describe the bug**

Kafka is showing 50K TPS, while Sink is showing only 4K TPS.

image_udsource-bug

### PR DESCRIPTION
**Pull request by yhl25**
fixes #1611

### CODE REVIEW

**Review by vigith — APPROVED** [review]

**Review by whynowy — APPROVED** [review]

File: pkg/sources/udsource/utils/offset.go [hunk 1]
```diff
@@ -56,12 +60,9 @@ func (s *simpleSourceOffset) NoAck() error {
 }
 
 func ConvertToSourceOffset(offset isb.Offset) *sourcepb.Offset {
+	decoded, _ := base64.StdEncoding.DecodeString(offset.String())
```
Comment (qhuai) [inline pkg/sources/udsource/utils/offset.go:63]: Could DecodeString ever fail?

Comment (yhl25) [reply pkg/sources/udsource/utils/offset.go:63]: With us controlling the encoding, `DecodeString` should never fail.

**Review by KeranYang — COMMENTED** [review]
Thank you @yhl25  for root causing and fixing this. My understanding is adding jetstream dedup metric helps with debugging the issue and adding partition index to write message id fixes the issue. Do we need the other changes under `udsource` folder and `utils` folder? I agree that base64 encoding is safer than `string()`.

File: pkg/sources/udsource/utils/offset.go [hunk 2]
```diff
@@ -17,21 +17,25 @@ limitations under the License.
...
 
-func NewSimpleSourceOffset(o string, p int32) isb.Offset {
+func NewSimpleSourceOffset(offset *sourcepb.Offset) isb.Offset {
 	return &simpleSourceOffset{
-		offset:       o,
-		partitionIdx: p,
+		offset:       base64.StdEncoding.EncodeToString(offset.GetOffset()),
+		partitionIdx: offset.GetPartitionId(),
 	}
 }
```
Comment (KeranYang) [inline pkg/sources/udsource/utils/offset.go:41]: Should we include partitionIdx in the `String()` of offset as you did in your first commit of the PR? Since partitionIdx is now an integral part of simpleSourceOffset.

**Review by KeranYang — APPROVED** [review]

**Review by vigith — CHANGES_REQUESTED** [review]
based on our meeting we need a few more changes

**Review by vigith — APPROVED** [review]
