### PR TITLE
fix: retry when getting EOF error at E2E test

### LINKED ISSUE #210: Flaky E2E tests caused by port-forward and logs streaming
Using port-forward to verify the testing results from Pod logs is widely used in E2E tests, which became unreliable recently - sometimes it fails with message like below, which means streaming logs fails, and usually a retry makes through.

```
Watching POD: simple-pipeline-watermark-cat3-0-np6xu
error: Get "https://172.18.0.3:10250/containerLogs/numaflow-system/simple-pipeline-watermark-cat3-0-np6xu/main?follow=true": EOF    functional_test.go:180: Expected vertex pod log contains "Start processing udf messages"
```

This issue could be caused by:

1. The runner instances assigned by Github action has limited resources - this issue started to happen after we had more test cases;
2. Unknown bugs in our code - log streaming or port-forward not released?
3. k3s version matters (v1.21 worked well, v1.21+ became flaky).

Long termly, we need to figure out a way to run E2E tests with a new approach.

### PR DESCRIPTION
**Pull request by KeranYang**
This change partially resolves #210. By adding retrying logic on pod log stream initialization and port forwarding, I was able to resolve two kinds of EOF errors, which are two of the most frequent causes of E2E test failure.

More investigation notes in https://github.com/numaproj/numaflow/issues/210#issuecomment-1293627883

Error 1
```
Watching POD: simple-pipeline-watermark-cat3-0-np6xu
error: Get "https://172.18.0.3:10250/containerLogs/numaflow-system/simple-pipeline-watermark-cat3-0-np6xu/main?follow=true": EOF    functional_test.go:180: Expected vertex pod log contains "Start processing udf messages"
```
and Error 2

```
functional_test.go:39: Vertex POD name: simple-pipeline-input-0-fpizv
panic: error upgrading connection: error dialing backend: EOF
```

### Testing
The following E2E test runs show in the log that the retry is getting invoked, which helps passing the E2E tests.
* Retrying on Error 1 - https://github.com/numaproj/numaflow/actions/runs/3346765321/jobs/5544895739
* Retrying on Error 2 - https://github.com/KeranYang/numaflow/actions/runs/3341257920/jobs/5532282295

Signed-off-by: Keran Yang <yangkr920208@gmail.com>

### CODE REVIEW

File: test/fixtures/port_forward.go [hunk 1]
```diff
@@ -37,12 +37,23 @@ func PodPortForward(config *rest.Config, namespace, podName string, localPort, r
 	}
 
 	go func() {
-		if err := fw.ForwardPorts(); err != nil {
+		// Port forwarding can fail due to transient "error upgrading connection: error dialing backend: EOF" issue.
+		// To prevent such issue, we apply retry strategy.
+		// 3 attempts with 1 second fixed wait time are tested sufficient for it.
+		err := retryOnError(3, time.Duration(1*time.Second), func() error {
```
Comment (whynowy) [inline test/fixtures/port_forward.go:43]: Use the existing backoff retry, find the examples from the code base.

**Review by vigith — APPROVED** [review]
