### PR TITLE
fix: break from retry loop when key is not found

### LINKED ISSUE #1536: Delete KeyValue entry from the watermark bucket when the processor goes down

### LINKED ISSUE #1540: Add unit tests for KeyValue store and watcher

### PR DESCRIPTION
**Pull request by yhl25**
* update the nats sdk
* avoid retrying forever when the key is not found 
* unit tests for kv store 
* update the Watch() function signature to avoid race condition between updates and done channel

Closes #1540 
Closes #1536

### CODE REVIEW

File: pkg/shared/kvs/jetstream/kv_store.go [hunk 1]
```diff
@@ -289,22 +290,28 @@ retryLoop:
...
 				time.Sleep(100 * time.Millisecond)
+				value, err = jss.kv.Get(key)
 			}
 		}
 		if value.Created().After(lastUpdate) {
 			lastUpdate = value.Created()
 		}
 	}
+
+	_ = keyLister.Stop()
```
Comment (vigith) [inline pkg/shared/kvs/jetstream/kv_store.go:314]: will we end up in double stopping because KeyLister closes stop if all is read?

File: pkg/shared/kvs/jetstream/kv_store.go [hunk 2]
```diff
@@ -289,22 +290,28 @@ retryLoop:
 
 	}
 
-	for _, key := range keys {
+	for key := range keyLister.Keys() {
 		value, err = jss.kv.Get(key)
 		for err != nil {
+			// keys can be deleted when the previous vertex pod is deleted/restarted.
+			if errors.Is(err, nats.ErrKeyNotFound) {
```
Comment (vigith) [inline pkg/shared/kvs/jetstream/kv_store.go:297]: let's add a Info statement here.

File: pkg/shared/kvs/jetstream/kv_store.go (hunk 1 above)
Comment (whynowy) [reply pkg/shared/kvs/jetstream/kv_store.go:314]: Shall we use `defer`?

File: test/idle-source-e2e/idle_source_test.go [hunk 3]
```diff
@@ -47,15 +47,16 @@ func (is *IdleSourceSuite) TestIdleKeyedReducePipeline() {
 	done := make(chan struct{})
 	go func() {
 		// publish messages to source vertex, with event time starting from 1000
```
Comment (vigith) [inline test/idle-source-e2e/idle_source_test.go:49]:
```suggestion
		// publish messages to source vertex, with event time starting from 0
```

**Review by vigith — APPROVED** [review]
