### PR TITLE
fix: timestamp and level filter fix for logs

### LINKED ISSUE #2341: Log level filtering not working as expected.
**Describe the bug**

When there's logs with corresponding log level, it displays previous logs with alert.

Image

**How to reproduce**

Create a [simple pipeline](https://github.com/numaproj/numaflow/blob/main/examples/1-simple-pipeline.yaml) and check the sink pod logs, play around the log levels.

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

### LINKED ISSUE #2342: Adding/Removing timestamps not working as expected
**Describe the bug**

Image
Image

**To Reproduce**

Create a [simple pipeline](https://github.com/numaproj/numaflow/blob/main/examples/1-simple-pipeline.yaml) and check the pod logs from different vertices, try out the add/remove timestamps feature.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

### LINKED ISSUE #2354: Enhance logs to include timestamp data to provide timestamp for timestamp toggle filter
Logs emitted by different vertex do not have a uniform format. For some vertices timestamp data is present in the log object, but for others it is appended as a string in the beginning. 
This caused the issue #2342 
Example - for a simple pipeline
cat vertex has `ts` object in the logs to determine timestamp

Image

sink vertex has log appended in the beginning as a string causing difference in format

Image

### PR DESCRIPTION
**Pull request by veds-g**
Timestamp is added to all logs from K8S API. 
'All' filter will show all logs and only logs with level info / name will come under respective filter.
Fixes #2354 
Fixes #2341 
Fixes #2342

### CODE REVIEW

File: ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx [hunk 1]
```diff
@@ -50,92 +47,41 @@ const parsePodLogs = (
 ): string[] => {
   const rawLogs = value.split("\n").filter((s) => s.length);
   return rawLogs.map((raw: string) => {
-    try {
-      if (type === "monoVertex") {
-        const msg = raw;
-        if (levelFilter !== "all" && !msg.toLowerCase().includes(levelFilter)) {
+    // 30 characters for RFC 3339 timestamp
+    const timestamp = raw.substring(0, 30);
```
Comment (adarsh0728) [inline ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx:51]: though timestamps are added, can we still have an additional check here before slicing

```
const timestamp = raw.length >= 31 ? raw.substring(0, 30) : "";
const logWithoutTimestamp = raw.length >= 31 ?  raw.substring(31) : raw;
```

File: ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx [hunk 2]
```diff
@@ -50,92 +47,41 @@ const parsePodLogs = (
 ): string[] => {
   const rawLogs = value.split("\n").filter((s) => s.length);
```
Comment (adarsh0728) [inline ui/src/components/pages/Pipeline/partials/Graph/partials/NodeInfo/partials/Pods/partials/PodDetails/partials/PodLogs/index.tsx:48]: can we use `s.trim().length` to remove empty lines

**Review by yhl25 — APPROVED** [review]

**Review by adarsh0728 — APPROVED** [review]
