### PR TITLE
fix: have `make pre-push -B` pass

### LINKED ISSUE #2565: `make codegen` failed with many `rm: cannot remove [..]: Permission denied`
**Describe the bug**

`make codegen` failed with many `rm: cannot remove [..]: Permission denied` as below. See the Screenshot section to check out whole the logs.

```
++++++++++++++++++++++++++++++++
++++ GENERATING PROTO FILES ++++
++++++++++++++++++++++++++++++++
[..]
pkg/apis/proto/daemon/daemon.proto:22:1: warning: Import google/protobuf/empty.proto is unused.
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/pkg/include/funcdata.h': Permission denied
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/pkg/include/asm_ppc64x.h': Permission denied
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/pkg/include/asm_riscv64.h': Permission denied
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/pkg/include/asm_amd64.h': Permission denied
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/pkg/include/textflag.h': Permission denied
[..]
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/SECURITY.md': Permission denied
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/bin/go': Permission denied
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/bin/gofmt': Permission denied
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/VERSION': Permission denied
rm: cannot remove '/tmp/tmp.C4WKeEqV6l/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.1.linux-amd64/codereview.cfg': Permission denied
make: *** [Makefile:235: codegen] Error 1
```

I found that the cause was probably `./hack/generate-proto.sh` failed.

Also `make pre-push -B` (written in PR template) failed because it depends on `codegen`.

**To Reproduce**

1. Run any of the following commands:
    - `make pre-push -B`
    - `make codegen`
    - `./hack/generate-proto.sh`

**Expected behavior**

Any of them above passes.

**Screenshots**

* [01-make-pre-push-B-fails.log](https://github.com/user-attachments/files/19881191/01-make-pre-push-B-fails.log)
* [02-make-codegen-fails.log](https://github.com/user-attachments/files/19881195/02-make-codegen-fails.log)
* [03-hack-generate-proto-fails.log](https://github.com/user-attachments/files/19881255/03-hack-generate-proto-fails.log)

**Environment (please complete the following information):**

- make: 4.3
- go: 1.24.1
- protoc: 3.21.12
- Numaflow: commit d1bb56627695b0b08f1464d42b1a6e2675b2733e

**Additional context**

The following comment can help us.

https://github.com/golang/go/issues/35615#issuecomment-554301773

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

>For quick help and support, join our [slack](https://numaproj.slack.com/join/shared_invite/zt-19svuv47m-YKHhsQ~~KK9mBv1E7pNzfg#/shared-invite/email) channel.

### PR DESCRIPTION
**Pull request by tmenjo**
Closes #2565 #2566

### CODE REVIEW

**Comment by tmenjo** [comment]
Here is a whole log `make pre-push -B` passed.

[01-make-pre-push-B-passes.log](https://github.com/user-attachments/files/19886089/01-make-pre-push-B-passes.log)

File: hack/generate-proto.sh [hunk 1]
```diff
@@ -10,6 +10,8 @@ header "generating proto files"
 ensure_vendor
 
 make_fake_paths
+# This overrides the existing trap
+trap 'cd "${FAKE_GOPATH}" && go clean -modcache && cd /tmp && rm -rf "${FAKE_GOPATH}"' EXIT
```
Comment (whynowy) [inline hack/generate-proto.sh:14]: This will leave existing temp file uncleaned up.

**Comment by whynowy** [comment]
We have seen this kind of issue before, caused by some version mismatch. Please make this on hold temporarily.

File: hack/generate-proto.sh (hunk 1 above)
Comment (whynowy) [inline hack/generate-proto.sh:14]: @tmenjo - The permission issue only happens when proto-gen fails right? So this change only cleans up the files, but does not solve your proto-gen failure, is my understanding correct?

Comment (tmenjo) [reply hack/generate-proto.sh:14]: In my words, the permission issue caused ./hack/generate-proto.sh to exit with non-zero code. Then it led to the failure of  `make codegen` and `make pre-push -B`.

When I removed (for testing purpose only) the existing `rm -rf ${FAKE_GOPATH}` trap registration in ./hack/library.sh, then ./hack/generate-proto.sh exited with 0. It meant that protoc or other commands in the script succeeded, though there are some warnings.

So the simple `rm -rf ${FAKE_GOPATH}` looked the root cause to me.

Comment (whynowy) [reply hack/generate-proto.sh:14]: hmmmm... I kind of know what was happening... I'll merge your PR, but will have a followup fix/dependency upgrade , and will ping you to see if that works in your env.

**Review by whynowy — APPROVED** [review]
