### PR TITLE
fix(UI): pending and ackPending buffer info on Edges

### LINKED ISSUE #2678: UI edge pending should show both pending and ack-pending
# Summary

Currently we show ack-pending as pending which is confusing. Perhaps we can show both

Image

Image

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by yogesh1801**
fixes #2678

### CODE REVIEW

**Comment by adarsh0728** [comment]
For testing:

- after making the changes, run `make image` from root dir
- Once `make image` succeeds, delete `numaflow-server` pod and then port forward the `numaflow-server` https://numaflow.numaproj.io/user-guide/UI/overview/#accessing-the-numaflow-ui 
- run a simple pipeline from examples directory (eg: https://github.com/numaproj/numaflow/blob/main/examples/1-simple-pipeline.yaml) 
   - If doing it for the first time, refer [quick start guide](https://numaflow.numaproj.io/quick-start/#creating-a-simple-pipeline)  
- verify your changes on the UI
   - if you want to test incremental UI changes, navigate to `ui` directory and run `yarn start ` - UI will get rendered on `localhost:3000`

**Comment by ygxio** [comment]
image


this is the output,  how do i put some numbers here?

File: ui/src/utils/fetcherHooks/pipelineViewFetch.ts [hunk 1]
```diff
@@ -540,23 +540,30 @@ export const usePipelineViewFetch = (
...
         const sidx = ns_pl.length;
         const eidx = buffer?.bufferName?.lastIndexOf("-");
         const id = buffer?.bufferName?.substring(sidx, eidx);
-        // condition check is similar for isFull so combining into one
-        if (edgeBackpressureLabel.get(id) === undefined) {
-          edgeBackpressureLabel.set(id, Number(buffer?.totalMessages));
+        
+        // Initialize or accumulate pending count
+        if (edgePendingLabel.get(id) === undefined) {
+          edgePendingLabel.set(id, Number(buffer?.pendingCount));
```
Comment (veds-g) [inline ui/src/utils/fetcherHooks/pipelineViewFetch.ts]: can we add a check if conversion of `Number(...) == NaN` then add `0` to the map? Similarly for all the below cases.

File: ui/src/utils/fetcherHooks/pipelineViewFetch.ts [hunk 2]
```diff
@@ -577,7 +584,9 @@ export const usePipelineViewFetch = (
           target: edge?.to,
           data: {
             conditions: edge?.conditions,
-            backpressureLabel: edgeBackpressureLabel.get(edge?.to),
+            pendingLabel: edgePendingLabel.get(edge?.to),
+            ackPendingLabel: edgeAckPendingLabel.get(edge?.to),
+            backpressureLabel: edgePendingLabel.get(edge?.to), // Keep for backward compatibility
```
Comment (veds-g) [inline ui/src/utils/fetcherHooks/pipelineViewFetch.ts]: we can remove this. Previous logic had total messages which were a sum of ackPending and pending.

Comment (ygxio) [reply ui/src/utils/fetcherHooks/pipelineViewFetch.ts]: u mean we can remove backpressure label?

File: ui/src/utils/fetcherHooks/pipelineViewFetch.ts [hunk 3]
```diff
@@ -653,7 +657,8 @@ export const usePipelineViewFetch = (
           if (vertex in vertexToHandleMap) {
             const handleID = vertexToHandleMap[vertex];
             const idSplit = handleID.split("-");
-            vertexToHandleMap[vertex] = "3-" + (Number(idSplit[1]) + 1);
+            const handleNumber = Number(idSplit[1]);
```
Comment (veds-g) [inline ui/src/utils/fetcherHooks/pipelineViewFetch.ts]: can we revert the NaN check here, as it seems to potentially create a different handle ID than expected?

File: ui/src/utils/fetcherHooks/pipelineViewFetch.ts (hunk 2 above)
Comment (veds-g) [reply ui/src/utils/fetcherHooks/pipelineViewFetch.ts]: yes

**Comment by ygxio** [comment]
I have done the fixes

**Review by veds-g — COMMENTED** [review]
LGTM. Thanks @yogesh1801 for taking this up.

**Review by veds-g — APPROVED** [review]
