### PR TITLE
chore: fix watermark components ownership

### LINKED ISSUE #962: flaky test: TestNewDataForward/batch_forward_basic
```
=== RUN   TestNewDataForward/batch_forward_basic
{"level":"info","ts":"2023-08-17T17:33:38.986890082Z","logger":"numaflow","caller":"forward/data_forward.go:127","msg":"Starting forwarder..."}
{"level":"info","ts":"2023-08-17T17:33:38.994098281Z","logger":"numaflow","caller":"publish/publisher.go:72","msg":"Creating a new watermark publisher","entityID":"testPipeline-testVertex-0","otStore":"noop","hbStore":"noop"}
    data_forward_test.go:1214: unexpected collecting result:
        
        metric output does not match expectation; want:
        
        # HELP source_forwarder_ack_total Total number of Messages Acknowledged
        # TYPE source_forwarder_ack_total counter
        source_forwarder_ack_total{partition_name="from",pipeline="testPipeline",vertex="testVertex"} 10
        
        got:
        
{"level":"info","ts":"2023-08-17T17:33:38.995441181Z","logger":"numaflow","caller":"publish/publisher.go:180","msg":"Skip publishing the new watermark because it's older than the current watermark","entityID":"testPipeline-testVertex-0","otStore":"noop","hbStore":"noop","toVertexPartitionIdx":0,"entity":"testPipeline-testVertex-0","head":-1,"new":-62135596800000}
{"level":"info","ts":"2023-08-17T17:33:38.995596881Z","logger":"numaflow","caller":"publish/publisher.go:180","msg":"Skip publishing the new watermark because it's older than the current watermark","entityID":"testPipeline-testVertex-0","otStore":"noop","hbStore":"noop","toVertexPartitionIdx":1,"entity":"testPipeline-testVertex-0","head":-1,"new":-62135596800000}
{"level":"info","ts":"2023-08-17T17:33:38.995524581Z","logger":"numaflow","caller":"publish/publisher.go:266","msg":"Publishing Heartbeat ticker started","entityID":"testPipeline-testVertex-0","otStore":"noop","hbStore":"noop"}
{"level":"info","ts":"2023-08-17T17:33:38.99612528Z","logger":"numaflow","caller":"forward/data_forward.go:139","msg":"Shutting down..."}
{"level":"info","ts":"2023-08-17T17:33:38.99618798Z","logger":"numaflow","caller":"forward/data_forward.go:157","msg":"Closed source reader","sourceFrom":"from"}
{"level":"info","ts":"2023-08-17T17:33:38.99625568Z","logger":"numaflow","caller":"forward/data_forward.go:164","msg":"Closed partition writer","bufferTo":"to1-1"}
{"level":"info","ts":"2023-08-17T17:33:38.99630038Z","logger":"numaflow","caller":"forward/data_forward.go:164","msg":"Closed partition writer","bufferTo":"to1-2"}
{"level":"info","ts":"2023-08-17T17:33:38.99633448
```

### PR DESCRIPTION
**Pull request by yhl25**
related to #900 

- publisher shouldn't close the store, it should just delete its key from the store, since it doesn't own it and in some cases, stores will be shared across publishers(for example Kafka source)
- for source, publishers should be closed inside the forwarder, since creation also happens inside the forwarder
- for the map, reduce and sink publishers and fetchers should be closed outside the forwarder because they don't own them and they are shared when there are multiple partitions 
- introduced `BuildProcessorManagers`, `BuildToVertexWatermarkStores` and  `BuildPublishersFromStores` helper functions
- removed `io.Closer` from `Fetcher` and `UXFetcher` interface.

also fixes #962

### CODE REVIEW

File: pkg/sinks/sink.go [hunk 1]
```diff
@@ -168,6 +194,30 @@ func (u *SinkProcessor) Start(ctx context.Context) error {
...
+		err = publisher.Close()
+		if err != nil {
+			log.Error("Failed to close the watermark publisher", zap.Error(err))
+		}
+	}
+
+	// close the wm stores, since the publisher and fetcher are closed
+	// since we created the stores, we can close them
+	for _, wmStore := range wmStores {
+		wmStore.HeartbeatStore().Close()
```
Comment (whynowy) [inline pkg/sinks/sink.go:217]: Add a `Close()` function to `WatermarkStore` interface ?

File: pkg/sinks/sink.go [hunk 2]
```diff
@@ -105,6 +104,33 @@ func (u *SinkProcessor) Start(ctx context.Context) error {
 			}
 			readers = append(readers, reader)
 		}
+
+		if u.VertexInstance.Vertex.Spec.Watermark.Disabled {
+			names := u.VertexInstance.Vertex.GetToBuffers()
+			if u.VertexInstance.Vertex.IsASink() {
+				// Sink has no to buffers, we use the vertex name as the buffer writer name.
+				names = append(names, u.VertexInstance.Vertex.Spec.Name)
```
Comment (whynowy) [inline pkg/sinks/sink.go:112]: Already know it's a sink, then the line above is not needed?

File: pkg/udf/reduce_udf.go [hunk 3]
```diff
@@ -246,21 +275,32 @@ func (u *ReduceUDFProcessor) Start(ctx context.Context) error {
...
 	<-ctx.Done()
 
-	// Close the watermark fetcher and publisher
+	log.Info("SIGTERM, exiting...")
+	wg.Wait()
+
+	// close the watermark fetcher and publisher since we created them
 	err = fetchWatermark.Close()
 	if err != nil {
 		log.Error("Failed to close the watermark fetcher", zap.Error(err))
```
Comment (whynowy) [inline pkg/udf/reduce_udf.go:284]: `log.Errorw()`

File: pkg/udf/map_udf.go [hunk 4]
```diff
@@ -214,18 +245,29 @@ func (u *MapUDFProcessor) Start(ctx context.Context) error {
 	// wait for all the forwarders to exit
 	finalWg.Wait()
 
-	// Close the watermark fetcher and publisher
+	// close the watermark fetcher and publisher since we created them
 	err = fetchWatermark.Close()
 	if err != nil {
 		log.Error("Failed to close the watermark fetcher", zap.Error(err))
```
Comment (whynowy) [inline pkg/udf/map_udf.go:251]: `Errorw()`

File: pkg/watermark/fetch/edge_fetcher.go [hunk 5]
```diff
@@ -198,7 +198,6 @@ func (e *edgeFetcher) updateHeadIdleWMB(fromPartitionIdx int32) wmb.WMB {
 
 // Close function stops the processor manager.
 func (e *edgeFetcher) Close() error {
-	e.processorManager.Stop()
```
Comment (whynowy) [inline pkg/watermark/fetch/edge_fetcher.go:201]: Who does it right now?

File: pkg/sinks/sink.go (hunk 2 above)
Comment (yhl25) [reply pkg/sinks/sink.go]: done

File: pkg/watermark/fetch/edge_fetcher.go (hunk 5 above)
Comment (yhl25) [reply pkg/watermark/fetch/edge_fetcher.go:201]: Stop() function will execute at the point of its creation, which could be within the map_udf or reduce_udf functions.

File: pkg/isbsvc/jetstream_service.go [hunk 6]
```diff
@@ -316,9 +315,9 @@ func (jss *jetStreamSvc) GetBufferInfo(ctx context.Context, buffer string) (*Buf
 	return bufferInfo, nil
 }
 
-// CreateUXWatermarkFetcher is used to create watermark fetcher for the given bucket.
-func (jss *jetStreamSvc) CreateUXWatermarkFetcher(ctx context.Context, bucketName string, fromBufferPartitionCount int, isReduce bool) ([]fetch.UXFetcher, error) {
-	var watermarkFetchers []fetch.UXFetcher
+// CreateProcessorManagers is used to create watermark fetcher for the given bucket.
+func (jss *jetStreamSvc) CreateProcessorManagers(ctx context.Context, bucketName string, fromBufferPartitionCount int, isReduce bool) ([]*processor.ProcessorManager, error) {
```
Comment (KeranYang) [inline pkg/isbsvc/jetstream_service.go:319]: Would it be better if we separate this interface into two `CreateWatermarkStores()` and `CreateProcessorManagers`? From the ownership perspective, the processor managers don't own the stores, hence the store creation is better to be independent of the processor manager's creation.

**Review by KeranYang — COMMENTED** [review]
Thank you very much for making this change. The ownership among fetcher, publisher, processor manger and kv stores are much clearer now. +1

File: pkg/udf/map_udf.go [hunk 7]
```diff
@@ -94,13 +102,36 @@ func (u *MapUDFProcessor) Start(ctx context.Context) error {
...
-		fetchWatermark, publishWatermark, err = jetstream.BuildWatermarkProgressors(ctx, u.VertexInstance, natsClientPool.NextAvailableClient())
-		if err != nil {
-			return err
-		}
-		readers, writers, err = buildJetStreamBufferIO(ctx, u.VertexInstance, natsClientPool)
-		if err != nil {
-			return err
+		if u.VertexInstance.Vertex.Spec.Watermark.Disabled {
+			names := u.VertexInstance.Vertex.GetToBuffers()
+			if u.VertexInstance.Vertex.IsASink() {
```
Comment (whynowy) [inline pkg/udf/map_udf.go:107]: Remove it.

File: pkg/udf/reduce_udf.go [hunk 8]
```diff
@@ -106,13 +112,36 @@ func (u *ReduceUDFProcessor) Start(ctx context.Context) error {
...
-		fetchWatermark, publishWatermark, err = jetstream.BuildWatermarkProgressors(ctx, u.VertexInstance, natsClientPool.NextAvailableClient())
-		if err != nil {
-			return err
-		}
-		readers, writers, err = buildJetStreamBufferIO(ctx, u.VertexInstance, natsClientPool)
-		if err != nil {
-			return err
+		if u.VertexInstance.Vertex.Spec.Watermark.Disabled {
+			names := u.VertexInstance.Vertex.GetToBuffers()
+			if u.VertexInstance.Vertex.IsASink() {
```
Comment (whynowy) [inline pkg/udf/reduce_udf.go:117]: Remove it.

File: pkg/sinks/sink.go [hunk 9]
```diff
@@ -105,6 +104,31 @@ func (u *SinkProcessor) Start(ctx context.Context) error {
 			}
 			readers = append(readers, reader)
 		}
+
+		if u.VertexInstance.Vertex.Spec.Watermark.Disabled {
+			names := u.VertexInstance.Vertex.GetToBuffers()
+			// sink has no to buffers, so we use the vertex name to publish the watermark
+			names = append(names, u.VertexInstance.Vertex.Spec.Name)
```
Comment (whynowy) [inline pkg/sinks/sink.go:111]: `names := []string{u.VertexInstance.Vertex.Spec.Name}`

File: pkg/isbsvc/jetstream_service.go (hunk 6 above)
Comment (jy4096) [reply pkg/isbsvc/jetstream_service.go:319]: you meant `CreateWatermarkWatchers()` ?...

File: pkg/sources/source.go [hunk 10]
```diff
@@ -99,15 +105,22 @@ func (sp *SourceProcessor) Start(ctx context.Context) error {
...
+		// create watermark fetcher using processor managers
+		fetchWatermark = fetch.NewSourceFetcher(ctx, processorManagers[sp.VertexInstance.Vertex.Name])
+
+		// build publisher stores for to vertex
+		toVertexWatermarkStores, err = jetstream.BuildToVertexWatermarkStores(ctx, sp.VertexInstance, natsClientPool.NextAvailableClient())
 		if err != nil {
 			return err
 		}
+
+		// build publisher stores for source (we publish twice for source)
```
Comment (jy4096) [inline pkg/sources/source.go:123]: could you add a comment here to explain why we need two sets of publisher stores?..

**Review by whynowy — APPROVED** [review]

**Review by vigith — APPROVED** [review]
We need to rename these, using `BuildProcessorManagers` to build `fetchers`, and `BuildToVertexWatermarkStores` to build `publishers` does not make sense.

The code should be self-documenting, as of now, it is quite difficult for a casual reader to understand the code.

### Fetch
```go
processorManagers, err = jetstream.BuildProcessorManagers(ctx, u.VertexInstance, natsClientPool.NextAvailableClient())

// create watermark fetcher using processor managers
fetchWatermark = fetch.NewEdgeFetcherSet(ctx, u.VertexInstance, processorManagers)
```



### Publish
```go
// create watermark stores
wmStores, err = jetstream.BuildToVertexWatermarkStores(ctx, u.VertexInstance, natsClientPool.NextAvailableClient())


// create watermark publisher using watermark stores
publishWatermark = jetstream.BuildPublishersFromStores(ctx, u.VertexInstance, wmStores)

readers, writers, err = buildJetStreamBufferIO(ctx, u.VertexInstance, natsClientPool)
```
