### PR TITLE
fix: GetHeadWatermark Logic

### LINKED ISSUE #632: Flaky E2E test - TestBuiltinEventTimeExtractor
TestBuiltinEventTimeExtractor is flaky.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by chromevoid**
Fixes #632

### CODE REVIEW

**Comment by vigith** [comment]
@chromevoid,

Could you please look into this `--- FAIL: TestFunctionalSuite/TestBuiltinEventTimeExtractor (64.98s)`? THis is the same event-time extractor @KeranYang was talking about.

File: test/e2e/functional_test.go [hunk 1]
```diff
@@ -190,35 +189,48 @@ func (s *FunctionalSuite) TestBuiltinEventTimeExtractor() {
...
+				assert.NoError(s.T(), err)
+				if err != nil {
+					println("error - ", err.Error())
+				}
+				// Watermark propagation can delay, we consider the test as passed as long as the retrieved watermark matches one of the assigned event times.
+				assert.True(s.T(), edgeWM == time.Date(2021, 5, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 4, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 3, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 2, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 1, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 5, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli())
+				break wmLoop
+			}
+			w.SendMessageTo(pipelineName, "in", NewHttpPostRequest().WithBody([]byte(testMsgFive)))
+			time.Sleep(time.Second)
```
Comment (KeranYang) [inline test/e2e/functional_test.go:231]: My understanding: with this change, we are sending a batch with message [2,3,4,5] and if we don't see expected wm, we send message 5 again as a mechanism to wait for watermark propagation.

If my understanding is correct, then 1. should we **NOT** expect `edgeWM == time.Date(2021, 5, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli()` ? There is no evidence that we have finished processing that event time right? and 2. As message [2,3,4,5] are one batch and http publishes wm using oldest message event time, should we always expecting edgeWM == time.Date(2021, 2, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli()?

Comment (vigith) [reply test/e2e/functional_test.go:231]: The source watermark has an inherent problem because it does not use offsets, and we end up using the head watermark. The so-called problem can be overlooked because a source (at the partition level) has to obey the monotonicity w.r.t event time. This means it is okay to have `edgeWM == time.Date(2021, 5, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli()`

File: test/e2e/functional_test.go [hunk 2]
```diff
@@ -190,35 +189,48 @@ func (s *FunctionalSuite) TestBuiltinEventTimeExtractor() {
...
+	w.SendMessageTo(pipelineName, "in", NewHttpPostRequest().WithBody([]byte(testMsgOne)))
 	w.Expect().VertexPodLogContains("out", fmt.Sprintf("EventTime -  %d", time.Date(2021, 1, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli()), PodLogCheckOptionWithCount(1))
 
 	// Verify watermark is generated based on the new event time.
 	testMsgTwo := `{"test": 21, "item": [{"id": 1, "name": "numa", "time": "2022-02-18T21:54:42.123Z"},{"id": 2, "name": "numa", "time": "2021-02-18T21:54:42.123Z"}]}`
 	testMsgThree := `{"test": 21, "item": [{"id": 1, "name": "numa", "time": "2022-02-18T21:54:42.123Z"},{"id": 2, "name": "numa", "time": "2021-03-18T21:54:42.123Z"}]}`
 	testMsgFour := `{"test": 21, "item": [{"id": 1, "name": "numa", "time": "2022-02-18T21:54:42.123Z"},{"id": 2, "name": "numa", "time": "2021-04-18T21:54:42.123Z"}]}`
 	testMsgFive := `{"test": 21, "item": [{"id": 1, "name": "numa", "time": "2022-02-18T21:54:42.123Z"},{"id": 2, "name": "numa", "time": "2021-05-18T21:54:42.123Z"}]}`
-	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
+	ctx, cancel := context.WithTimeout(context.Background(), 400*time.Second)
```
Comment (vigith) [inline test/e2e/functional_test.go:201]:
```suggestion
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
```

**Review by vigith — APPROVED** [review]

File: pkg/watermark/fetch/edge_fetcher.go [hunk 3]
```diff
@@ -104,17 +104,22 @@ func (e *edgeFetcher) GetHeadWatermark() wmb.Watermark {
...
-			headOffset = w.Offset
-			epoch = w.Watermark
+		if w.Offset != -1 {
+			// find the smallest head offset of the smallest watermark
+			if w.Watermark < headWatermark {
+				headOffset = w.Offset
+				headWatermark = w.Watermark
+			} else if w.Watermark == headWatermark && w.Offset < headOffset {
+				headOffset = w.Offset
+			}
```
Comment (KeranYang) [inline pkg/watermark/fetch/edge_fetcher.go:114]: This is a change of logic. Could you add some unit tests for it?

File: test/e2e/functional_test.go [hunk 4]
```diff
@@ -190,35 +189,48 @@ func (s *FunctionalSuite) TestBuiltinEventTimeExtractor() {
...
+		default:
+			wm, err := client.GetPipelineWatermarks(ctx, pipelineName)
+			edgeWM := wm[0].Watermarks[0]
+			if wm[0].Watermarks[0] != -1 {
+				assert.NoError(s.T(), err)
+				if err != nil {
+					assert.Fail(s.T(), err.Error())
+				}
+				// Watermark propagation can delay, we consider the test as passed as long as the retrieved watermark matches one of the assigned event times.
+				assert.True(s.T(), edgeWM == time.Date(2021, 5, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 4, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 3, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 2, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 1, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli() || edgeWM == time.Date(2021, 5, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli())
```
Comment (KeranYang) [inline test/e2e/functional_test.go:227]: There are two `edgeWM == time.Date(2021, 5, 18, 21, 54, 42, 123000000, time.UTC).UnixMilli()`, please remove one of them.

File: test/e2e/testdata/extract-event-time-from-payload.yaml [hunk 5]
```diff
@@ -5,6 +5,10 @@ metadata:
 spec:
   vertices:
     - name: in
+      containerTemplate:
```
Comment (KeranYang) [inline test/e2e/testdata/extract-event-time-from-payload.yaml:8]: Please clean up.

Comment (yhl25) [reply test/e2e/testdata/extract-event-time-from-payload.yaml:8]: there is no harm in running e2e tests in debug mode

Comment (KeranYang) [reply test/e2e/testdata/extract-event-time-from-payload.yaml:8]: Personally I prefer having a standard when developing e2e tests. I see some of the e2e test cases turn on debug mode and most don't so I am thinking we should make it consistent. No strong opinion though.

**Review by KeranYang — APPROVED** [review]

File: pkg/watermark/fetch/edge_fetcher.go [hunk 6]
```diff
@@ -104,17 +103,19 @@ func (e *edgeFetcher) GetHeadWatermark() wmb.Watermark {
...
 		e.log.Debugf("Processor: %v (headOffset:%d) (headWatermark:%d) (headIdle:%t)", p, w.Offset, w.Watermark, w.Idle)
 		debugString.WriteString(fmt.Sprintf("[Processor:%v] (headOffset:%d) (headWatermark:%d) (headIdle:%t) \n", p, w.Offset, w.Watermark, w.Idle))
-		if w.Offset != -1 && w.Offset > headOffset {
-			headOffset = w.Offset
-			epoch = w.Watermark
+		if w.Offset != -1 {
+			// find the smallest watermark
+			if w.Watermark < headWatermark {
+				headWatermark = w.Watermark
+			}
```
Comment (chromevoid) [inline pkg/watermark/fetch/edge_fetcher.go:110]: I updated the logic because we don't need to return offset in this function...
