### PR TITLE
fix: send keys for udsink

### LINKED ISSUE #978: sinksdk Datum.Keys() is returning empty string list
**Describe the bug**
I have two sinks, built-in log sink and one udsink. When I log Datum.Keys() in udsink it is an empty list, but the previous vertex is sending output with Keys. Also, I can see Keys in the log sink output. 
So what is the reason for Datum.Keys to be empty for udsink

**To Reproduce**

1. Implement a UD Sink with previous vertex sending data with Keys

**Expected behavior**
Keys should have the expected keys list passed on from previous vertex 

**Screenshots**

**Environment (please complete the following information):**

Using numaflow-go sdk v0.4.5

- Kubernetes: [e.g. v1.18.6]
- Numaflow: [e.g. v0.5.1]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by yhl25**
fixes #978

### CODE REVIEW

File: pkg/sinks/udsink/sink.go [hunk 1]
```diff
@@ -111,6 +111,7 @@ func (s *UserDefinedSink) Write(ctx context.Context, messages []isb.Message) ([]
 			// NOTE: key is not used anywhere ATM
```
Comment (KeranYang) [inline pkg/sinks/udsink/sink.go:111]: Does this statement still hold true? 🤔

**Review by KeranYang — APPROVED** [review]

File: pkg/sinks/udsink/sink.go (hunk 1 above)
Comment (yhl25) [reply pkg/sinks/udsink/sink.go]: removed
